// test definitions: do not edit this file!
import student;
import boost.ut;


 auto main() -> int {
   using namespace boost::ut;
 
   "add"_test = [] {
     expect(add(1,1) == 2);
   };

   "mul"_test = [] {
    expect(mul(3,3) == 9);
  };
  return 0;
 }
